//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidacionesSoapServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/Validaciones/", ConfigurationName="ValidacionesSoapServiceReference.Validaciones")]
    public interface Validaciones
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Validaciones/validarNIF", ReplyAction="*")]
        System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarNIFResponse> validarNIFAsync(ValidacionesSoapServiceReference.validarNIFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Validaciones/validarNIE", ReplyAction="*")]
        System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarNIEResponse> validarNIEAsync(ValidacionesSoapServiceReference.validarNIERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Validaciones/validarNAF", ReplyAction="*")]
        System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarNAFResponse> validarNAFAsync(ValidacionesSoapServiceReference.validarNAFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Validaciones/validarIBAN", ReplyAction="*")]
        System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarIBANResponse> validarIBANAsync(ValidacionesSoapServiceReference.validarIBANRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNIFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNIF", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesSoapServiceReference.validarNIFRequestBody Body;
        
        public validarNIFRequest()
        {
        }
        
        public validarNIFRequest(ValidacionesSoapServiceReference.validarNIFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNIFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NIF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string WSKey;
        
        public validarNIFRequestBody()
        {
        }
        
        public validarNIFRequestBody(string NIF, string WSKey)
        {
            this.NIF = NIF;
            this.WSKey = WSKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNIFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNIFResponse", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesSoapServiceReference.validarNIFResponseBody Body;
        
        public validarNIFResponse()
        {
        }
        
        public validarNIFResponse(ValidacionesSoapServiceReference.validarNIFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNIFResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensajeSalida;
        
        public validarNIFResponseBody()
        {
        }
        
        public validarNIFResponseBody(bool valido, string mensajeSalida)
        {
            this.valido = valido;
            this.mensajeSalida = mensajeSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNIERequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNIE", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesSoapServiceReference.validarNIERequestBody Body;
        
        public validarNIERequest()
        {
        }
        
        public validarNIERequest(ValidacionesSoapServiceReference.validarNIERequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNIERequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NIE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string WSKey;
        
        public validarNIERequestBody()
        {
        }
        
        public validarNIERequestBody(string NIE, string WSKey)
        {
            this.NIE = NIE;
            this.WSKey = WSKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNIEResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNIEResponse", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesSoapServiceReference.validarNIEResponseBody Body;
        
        public validarNIEResponse()
        {
        }
        
        public validarNIEResponse(ValidacionesSoapServiceReference.validarNIEResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNIEResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensajeSalida;
        
        public validarNIEResponseBody()
        {
        }
        
        public validarNIEResponseBody(bool valido, string mensajeSalida)
        {
            this.valido = valido;
            this.mensajeSalida = mensajeSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNAFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNAF", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesSoapServiceReference.validarNAFRequestBody Body;
        
        public validarNAFRequest()
        {
        }
        
        public validarNAFRequest(ValidacionesSoapServiceReference.validarNAFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNAFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NAF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string WSKey;
        
        public validarNAFRequestBody()
        {
        }
        
        public validarNAFRequestBody(string NAF, string WSKey)
        {
            this.NAF = NAF;
            this.WSKey = WSKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNAFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNAFResponse", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesSoapServiceReference.validarNAFResponseBody Body;
        
        public validarNAFResponse()
        {
        }
        
        public validarNAFResponse(ValidacionesSoapServiceReference.validarNAFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNAFResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensajeSalida;
        
        public validarNAFResponseBody()
        {
        }
        
        public validarNAFResponseBody(bool valido, string mensajeSalida)
        {
            this.valido = valido;
            this.mensajeSalida = mensajeSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarIBANRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarIBAN", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesSoapServiceReference.validarIBANRequestBody Body;
        
        public validarIBANRequest()
        {
        }
        
        public validarIBANRequest(ValidacionesSoapServiceReference.validarIBANRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarIBANRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBAN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string WSKey;
        
        public validarIBANRequestBody()
        {
        }
        
        public validarIBANRequestBody(string IBAN, string WSKey)
        {
            this.IBAN = IBAN;
            this.WSKey = WSKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarIBANResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarIBANResponse", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesSoapServiceReference.validarIBANResponseBody Body;
        
        public validarIBANResponse()
        {
        }
        
        public validarIBANResponse(ValidacionesSoapServiceReference.validarIBANResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarIBANResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensajeSalida;
        
        public validarIBANResponseBody()
        {
        }
        
        public validarIBANResponseBody(bool valido, string mensajeSalida)
        {
            this.valido = valido;
            this.mensajeSalida = mensajeSalida;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ValidacionesChannel : ValidacionesSoapServiceReference.Validaciones, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ValidacionesClient : System.ServiceModel.ClientBase<ValidacionesSoapServiceReference.Validaciones>, ValidacionesSoapServiceReference.Validaciones
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ValidacionesClient() : 
                base(ValidacionesClient.GetDefaultBinding(), ValidacionesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ValidacionesSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidacionesClient(EndpointConfiguration endpointConfiguration) : 
                base(ValidacionesClient.GetBindingForEndpoint(endpointConfiguration), ValidacionesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidacionesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ValidacionesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidacionesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ValidacionesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarNIFResponse> ValidacionesSoapServiceReference.Validaciones.validarNIFAsync(ValidacionesSoapServiceReference.validarNIFRequest request)
        {
            return base.Channel.validarNIFAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarNIFResponse> validarNIFAsync(string NIF, string WSKey)
        {
            ValidacionesSoapServiceReference.validarNIFRequest inValue = new ValidacionesSoapServiceReference.validarNIFRequest();
            inValue.Body = new ValidacionesSoapServiceReference.validarNIFRequestBody();
            inValue.Body.NIF = NIF;
            inValue.Body.WSKey = WSKey;
            return ((ValidacionesSoapServiceReference.Validaciones)(this)).validarNIFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarNIEResponse> ValidacionesSoapServiceReference.Validaciones.validarNIEAsync(ValidacionesSoapServiceReference.validarNIERequest request)
        {
            return base.Channel.validarNIEAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarNIEResponse> validarNIEAsync(string NIE, string WSKey)
        {
            ValidacionesSoapServiceReference.validarNIERequest inValue = new ValidacionesSoapServiceReference.validarNIERequest();
            inValue.Body = new ValidacionesSoapServiceReference.validarNIERequestBody();
            inValue.Body.NIE = NIE;
            inValue.Body.WSKey = WSKey;
            return ((ValidacionesSoapServiceReference.Validaciones)(this)).validarNIEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarNAFResponse> ValidacionesSoapServiceReference.Validaciones.validarNAFAsync(ValidacionesSoapServiceReference.validarNAFRequest request)
        {
            return base.Channel.validarNAFAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarNAFResponse> validarNAFAsync(string NAF, string WSKey)
        {
            ValidacionesSoapServiceReference.validarNAFRequest inValue = new ValidacionesSoapServiceReference.validarNAFRequest();
            inValue.Body = new ValidacionesSoapServiceReference.validarNAFRequestBody();
            inValue.Body.NAF = NAF;
            inValue.Body.WSKey = WSKey;
            return ((ValidacionesSoapServiceReference.Validaciones)(this)).validarNAFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarIBANResponse> ValidacionesSoapServiceReference.Validaciones.validarIBANAsync(ValidacionesSoapServiceReference.validarIBANRequest request)
        {
            return base.Channel.validarIBANAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidacionesSoapServiceReference.validarIBANResponse> validarIBANAsync(string IBAN, string WSKey)
        {
            ValidacionesSoapServiceReference.validarIBANRequest inValue = new ValidacionesSoapServiceReference.validarIBANRequest();
            inValue.Body = new ValidacionesSoapServiceReference.validarIBANRequestBody();
            inValue.Body.IBAN = IBAN;
            inValue.Body.WSKey = WSKey;
            return ((ValidacionesSoapServiceReference.Validaciones)(this)).validarIBANAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidacionesSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidacionesSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/Prac1-prueba-v2/services/Validaciones/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ValidacionesClient.GetBindingForEndpoint(EndpointConfiguration.ValidacionesSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ValidacionesClient.GetEndpointAddress(EndpointConfiguration.ValidacionesSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            ValidacionesSOAP,
        }
    }
}
