//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/Empleados/", ConfigurationName="ServiceReference2.Empleados")]
    public interface Empleados
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Empleados/nuevo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.nuevoResponse> nuevoAsync(ServiceReference2.nuevoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Empleados/borrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.borrarResponse> borrarAsync(ServiceReference2.borrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Empleados/modificar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.modificarResponse> modificarAsync(ServiceReference2.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Empleados/consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.consultarResponse> consultarAsync(ServiceReference2.consultarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/Empleados/")]
    public partial class EmpleadosType
    {
        
        private string nifnieField;
        
        private string nombreApellidosField;
        
        private string emailField;
        
        private string nafField;
        
        private string ibanField;
        
        private int idNivelField;
        
        private string usuarioField;
        
        private string passwordField;
        
        private int validoField;
        
        private int idField;
        
        private string wSKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nifnie
        {
            get
            {
                return this.nifnieField;
            }
            set
            {
                this.nifnieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreApellidos
        {
            get
            {
                return this.nombreApellidosField;
            }
            set
            {
                this.nombreApellidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string naf
        {
            get
            {
                return this.nafField;
            }
            set
            {
                this.nafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string iban
        {
            get
            {
                return this.ibanField;
            }
            set
            {
                this.ibanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idNivel
        {
            get
            {
                return this.idNivelField;
            }
            set
            {
                this.idNivelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int valido
        {
            get
            {
                return this.validoField;
            }
            set
            {
                this.validoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string WSKey
        {
            get
            {
                return this.wSKeyField;
            }
            set
            {
                this.wSKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nuevo", WrapperNamespace="http://www.example.org/Empleados/", IsWrapped=true)]
    public partial class nuevoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/Empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference2.EmpleadosType @in;
        
        public nuevoRequest()
        {
        }
        
        public nuevoRequest(ServiceReference2.EmpleadosType @in)
        {
            this.@in = @in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nuevoResponse", WrapperNamespace="http://www.example.org/Empleados/", IsWrapped=true)]
    public partial class nuevoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/Empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @out;
        
        public nuevoResponse()
        {
        }
        
        public nuevoResponse(string @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="borrar", WrapperNamespace="http://www.example.org/Empleados/", IsWrapped=true)]
    public partial class borrarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/Empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nifnie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/Empleados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WSKey;
        
        public borrarRequest()
        {
        }
        
        public borrarRequest(string nifnie, string WSKey)
        {
            this.nifnie = nifnie;
            this.WSKey = WSKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="borrarResponse", WrapperNamespace="http://www.example.org/Empleados/", IsWrapped=true)]
    public partial class borrarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/Empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @out;
        
        public borrarResponse()
        {
        }
        
        public borrarResponse(string @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://www.example.org/Empleados/", IsWrapped=true)]
    public partial class modificarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/Empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference2.EmpleadosType @in;
        
        public modificarRequest()
        {
        }
        
        public modificarRequest(ServiceReference2.EmpleadosType @in)
        {
            this.@in = @in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://www.example.org/Empleados/", IsWrapped=true)]
    public partial class modificarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/Empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @out;
        
        public modificarResponse()
        {
        }
        
        public modificarResponse(string @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar", WrapperNamespace="http://www.example.org/Empleados/", IsWrapped=true)]
    public partial class consultarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/Empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nifnie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/Empleados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WSKey;
        
        public consultarRequest()
        {
        }
        
        public consultarRequest(string nifnie, string WSKey)
        {
            this.nifnie = nifnie;
            this.WSKey = WSKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarResponse", WrapperNamespace="http://www.example.org/Empleados/", IsWrapped=true)]
    public partial class consultarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/Empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference2.EmpleadosType @out;
        
        public consultarResponse()
        {
        }
        
        public consultarResponse(ServiceReference2.EmpleadosType @out)
        {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface EmpleadosChannel : ServiceReference2.Empleados, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class EmpleadosClient : System.ServiceModel.ClientBase<ServiceReference2.Empleados>, ServiceReference2.Empleados
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmpleadosClient() : 
                base(EmpleadosClient.GetDefaultBinding(), EmpleadosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EmpleadosSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosClient(EndpointConfiguration endpointConfiguration) : 
                base(EmpleadosClient.GetBindingForEndpoint(endpointConfiguration), EmpleadosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmpleadosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmpleadosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.nuevoResponse> ServiceReference2.Empleados.nuevoAsync(ServiceReference2.nuevoRequest request)
        {
            return base.Channel.nuevoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.nuevoResponse> nuevoAsync(ServiceReference2.EmpleadosType @in)
        {
            ServiceReference2.nuevoRequest inValue = new ServiceReference2.nuevoRequest();
            inValue.@in = @in;
            return ((ServiceReference2.Empleados)(this)).nuevoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.borrarResponse> ServiceReference2.Empleados.borrarAsync(ServiceReference2.borrarRequest request)
        {
            return base.Channel.borrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.borrarResponse> borrarAsync(string nifnie, string WSKey)
        {
            ServiceReference2.borrarRequest inValue = new ServiceReference2.borrarRequest();
            inValue.nifnie = nifnie;
            inValue.WSKey = WSKey;
            return ((ServiceReference2.Empleados)(this)).borrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.modificarResponse> ServiceReference2.Empleados.modificarAsync(ServiceReference2.modificarRequest request)
        {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.modificarResponse> modificarAsync(ServiceReference2.EmpleadosType @in)
        {
            ServiceReference2.modificarRequest inValue = new ServiceReference2.modificarRequest();
            inValue.@in = @in;
            return ((ServiceReference2.Empleados)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.consultarResponse> ServiceReference2.Empleados.consultarAsync(ServiceReference2.consultarRequest request)
        {
            return base.Channel.consultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.consultarResponse> consultarAsync(string nifnie, string WSKey)
        {
            ServiceReference2.consultarRequest inValue = new ServiceReference2.consultarRequest();
            inValue.nifnie = nifnie;
            inValue.WSKey = WSKey;
            return ((ServiceReference2.Empleados)(this)).consultarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmpleadosSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmpleadosSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/Prac1-prueba-v2/services/Empleados/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EmpleadosClient.GetBindingForEndpoint(EndpointConfiguration.EmpleadosSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EmpleadosClient.GetEndpointAddress(EndpointConfiguration.EmpleadosSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            EmpleadosSOAP,
        }
    }
}
